services: 
  reverse-proxy:
    image: nginx:1.27
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    labels:
     - "traefik.http.routers.24-25-projectopdracht-devops-3bdoAP.rule=Host(`todo-49-12-38-139.traefik.me`)"
    networks:
     - traefik
  api:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=todoUser
      - MYSQL_PWD=DitIsGoed
      - MYSQL_DB=todo
    networks:
      - traefik

  db:
    image: mysql
    volumes:
      - db-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   
    environment:
      - MYSQL_ROOT_PASSWORD=DitIsGoed
      - MYSQL_USER=todoUser
      - MYSQL_PASSWORD=DitIsGoed
      - MYSQL_DATABASE=todo
    networks:
      - traefik
volumes:
  db-volume:
networks:
  traefik:
   external: true
   name: traefik
