services: 
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  api:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=todoUser
      - MYSQL_PWD=DitIsGoed
      - MYSQL_DB=todo

  db:
    image: mysql
    volumes:
      - db-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   
    environment:
      - MYSQL_ROOT_PASSWORD=DitIsGoed
      - MYSQL_USER=todoUser
      - MYSQL_PASSWORD=DitIsGoed
      - MYSQL_DATABASE=todo

volumes:
  db-volume:
