services:
  reverse-proxy:
    image: nginx:1.27
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    labels:
     - "traefik.http.routers.24-25-projectopdracht-devops-3bdoAP.rule=Host(`abdallahtest.be`)"
    networks:
     - traefik
  api:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=${USER}
      - MYSQL_PWD=${PASS}
      - MYSQL_DB=${DB}
    networks:
      - traefik

  db:
    image: mysql
    volumes:
      - db-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=${DB}
    networks:
      - traefik
volumes:
  db-volume:
networks:
  traefik:
   external: true
   name: traefik
