entryPoints:
  web:
    address: ":80"
    http:

  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: abdallah11102003@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
providers:
  docker: {}
  file:
    directory: "/etc/traefik/conf.d"
api:
  dashboard: true
